import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './main.scss'
import QueryWrapper from './auth/QueryWrapper'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Noted',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter}`}>
        <QueryWrapper>
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
